### ISSUE TITLE
Allow users to email registrations?

### ISSUE THREAD

**Issue by djensenius** [djensenius/parking#40]
Would prefer form used, but maybe we should allow users to email as well?

**Comment by tomh009** [comment]
The sender's email address is probably good enough for identification, but is it reasonable to parse the dates? I guess if the dates cannot be identified, we could send back a form email showing how to specify them.  e.g.
Licence: ABC-123
From: 2018-01-01
To: 2018-01-03

**Comment by djensenius** [comment]
No for now.
