### ISSUE TITLE
Mobile admin page orientation

### ISSUE THREAD

**Issue by tomh009** [djensenius/parking#57]
Force mobile admin page to list reservations in rows rather than columns

**Comment by djensenius** [comment]
I think this was addressed in #56 ? Could you verify?

**Comment by tomh009** [comment]
Yes, looks good now.  One related question: what is the sort order for the list?  I think maybe start date would make the most sense.

**Comment by djensenius** [comment]
Sorted by date they were created. I have a couple of issues created to create different pages or tabs, see #35 and #34. So this will be changing shortly, maybe even tonight. 🙂

**Comment by tomh009** [comment]
OK!
