### ISSUE TITLE
Enable CSV download

### ISSUE THREAD

**Issue by tomh009** [djensenius/parking#79]
Enable CSV download of historical data (future data not needed).  Ideal scenario will have a format of something like this, one row per date:
    date,make,licence plate,unit number
With this, a multi-night reservation would result in multiple records.

If the database format is not conducive to this, second choice is this format:
    start date,end date,make,licence plate,unit number

Please use yyyy-mm-dd date format. Being able to select a date range would be a nice-to-have but not required.

**Comment by djensenius** [comment]
Going to implement most basic version for now. Let's create separate issue(s) for cleanup.
